version: "3"
services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    ports:
      - "5380:5380/tcp" #DNS web console (HTTP)
      - "5353:53/udp" #DNS service
      - "5353:53/tcp" #DNS service
    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itself.
    volumes:
      - config:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
  web:
    image: nginx:alpine
    volumes:
      - ./sitio-web:/usr/share/nginx/html
    ports:
      - "80:80"
  ftp:
    image: fauria/vsftpd
    container_name: ftp_server
    ports:
      - "2020:20"
      - "2121:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./ftp_data:/home/vsftpd
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=yourpassword
      - PASV_ADDRESS=192.168.0.103
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    restart: unless-stopped

volumes:
    config:
